# Generated by Django 4.1.1 on 2023-05-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rating',
        ),

        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.item')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.item')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.size')),
            ],
        ),
        migrations.CreateModel(
            name='ItemComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.composition')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),

        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, through='backend.ItemTag', to='backend.tag'),
        ),
    ]
