# Generated by Django 4.1.1 on 2023-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_item_rating_itemtag_itemsize_itemcomposition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),

        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(through='backend.ItemTag', to='backend.tag'),
        ),

    ]
