# Generated by Django 4.1.1 on 2023-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='composition',
        ),

        migrations.AddField(
            model_name='item',
            name='composition',
            field=models.ManyToManyField(through='backend.ItemComposition', to='backend.composition'),
        ),

        migrations.RemoveField(
            model_name='item',
            name='sizes',
            
        ),

        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(through='backend.ItemSize', to='backend.size'),
        ),


    ]
