# Generated by Django 4.1.1 on 2023-05-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_item_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материал'},
        ),
        migrations.AlterModelOptions(
            name='itemcomposition',
            options={'verbose_name': 'Материалы', 'verbose_name_plural': 'Материал'},
        ),
        migrations.AlterModelOptions(
            name='itemsize',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='itemtag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размеры', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='item',
            name='composition',
            field=models.ManyToManyField(through='backend.ItemComposition', to='backend.composition', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(through='backend.ItemSize', to='backend.size', verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(through='backend.ItemTag', to='backend.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='itemcomposition',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.composition', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='itemcomposition',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.item', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.item', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='itemtag',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.item', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='itemtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.tag', verbose_name='Тег'),
        ),
    ]
